# Generated by Django 5.1.6 on 2025-03-10 08:27

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contador', models.BigIntegerField(editable=False, unique=True)),
                ('tipo_orden', models.CharField(choices=[('PRESUPUESTO', 'PRESUPUESTO'), ('VENTA', 'VENTA')], default='PRESUPUESTO', max_length=50, verbose_name='Tipo de Orden')),
                ('fecha_creacion', models.DateField(default=datetime.date.today, verbose_name='Fecha de Orden')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('estado_orden', models.CharField(choices=[('pendiente', 'Pendiente'), ('demorada', 'Demorada'), ('terminada', 'Terminada')], default='pendiente', max_length=50, verbose_name='Estado de Orden')),
                ('tiempo_entrega', models.DateField(blank=True, null=True, verbose_name='Tiempo de Entrega')),
                ('metros_totales', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metros² Totales')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente')),
                ('colocador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.colocador', verbose_name='Colocador')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['contador'],
            },
        ),
    ]
