# Generated by Django 5.1.6 on 2025-03-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='prioridad',
            field=models.BooleanField(default=False, verbose_name='Orden Prioritaria'),
        ),
    ]
