# Generated by Django 5.1.6 on 2025-03-29 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0002_ordentrabajo_prioridad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='contador',
        ),
    ]
