# Generated by Django 5.1.6 on 2025-02-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0002_alter_ordentrabajo_cliente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordentrabajo',
            old_name='descripcion',
            new_name='observaciones',
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='ganancia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Ganancia Neta'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='porcentaje_ganancia',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='% Ganancia'),
            preserve_default=False,
        ),
    ]
