# Generated by Django 5.1.6 on 2025-02-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0004_ordentrabajo_estado_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado_orden',
            field=models.CharField(choices=[('pendiente', 'pendiente'), ('demorada', 'demorada'), ('terminada', 'terminada')], default='pendiente', max_length=50, verbose_name='Estado de Orden'),
        ),
    ]
