# Generated by Django 5.1.6 on 2025-02-28 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_direccion_alter_cliente_email_and_more'),
        ('ordendetrabajo', '0005_alter_ordentrabajo_estado_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cliente.cliente', verbose_name='Cliente'),
        ),
    ]
