# Generated by Django 5.1.6 on 2025-03-02 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_colocador_alter_cliente_options_and_more'),
        ('ordendetrabajo', '0008_alter_ordentrabajo_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='colocador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cliente.colocador', verbose_name='Colocador'),
        ),
    ]
