# Generated by Django 5.1.6 on 2025-03-02 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0009_ordentrabajo_colocador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='tiempo_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Tiempo de Entrega'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='estado_orden',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('demorada', 'Demorada'), ('terminada', 'Terminada')], default='pendiente', max_length=50, verbose_name='Estado de Orden'),
        ),
    ]
