# Generated by Django 5.1.6 on 2025-03-02 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0010_ordentrabajo_tiempo_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tiempo_entrega',
            field=models.DateField(blank=True, null=True, verbose_name='Tiempo de Entrega'),
        ),
    ]
