# Generated by Django 5.1.6 on 2025-03-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0011_alter_ordentrabajo_tiempo_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='fecha_creacion',
        ),
    ]
