# Generated by Django 5.1.6 on 2025-03-02 18:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0012_remove_ordentrabajo_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Fecha de Orden'),
        ),
    ]
