# Generated by Django 5.1.6 on 2025-03-02 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0013_ordentrabajo_fecha_creacion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordentrabajo',
            options={'ordering': ['contador'], 'verbose_name': 'Orden de Trabajo', 'verbose_name_plural': 'Órdenes de Trabajo'},
        ),
        migrations.AddField(
            model_name='ordentrabajo',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
            preserve_default=False,
        ),
    ]
