# Generated by Django 5.1.6 on 2025-03-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0017_alter_ordentrabajo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='usuario',
            field=models.CharField(max_length=50, verbose_name='Usuario Creador'),
        ),
    ]
