# Generated by Django 5.1.6 on 2025-03-03 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0019_alter_ordentrabajo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordentrabajo',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha de Orden'),
        ),
    ]
