# Generated by Django 5.1.6 on 2025-03-03 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0020_alter_ordentrabajo_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordentrabajo',
            name='usuario',
        ),
    ]
