# Generated by Django 5.1.6 on 2025-03-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0021_remove_ordentrabajo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='Tipo_orden',
            field=models.CharField(choices=[('PRESUPUESTO', 'Presupuesto'), ('VENTA', 'Venta')], default='PRESUPUESTO', max_length=50, verbose_name='Tipo de Orden'),
        ),
    ]
