# Generated by Django 5.1.6 on 2025-03-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0022_ordentrabajo_tipo_orden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordentrabajo',
            old_name='Tipo_orden',
            new_name='tipo_orden',
        ),
    ]
