# Generated by Django 5.1.6 on 2025-03-03 18:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0023_rename_tipo_orden_ordentrabajo_tipo_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total'),
        ),
        migrations.AlterField(
            model_name='ordentrabajo',
            name='tipo_orden',
            field=models.CharField(choices=[('PRESUPUESTO', 'PRESUPUESTO'), ('VENTA', 'VENTA')], default='PRESUPUESTO', max_length=50, verbose_name='Tipo de Orden'),
        ),
    ]
