# Generated by Django 5.1.6 on 2025-03-03 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0024_ordentrabajo_total_alter_ordentrabajo_tipo_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordentrabajo',
            name='metros_totales',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metros² Totales'),
        ),
    ]
