# Generated by Django 5.1.6 on 2025-03-24 16:02

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInismos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadena', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Cadena')),
                ('zocalo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Zocalo')),
                ('tapa_zocalo', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tapa Zocalo')),
                ('peso_cadena', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Cadena')),
                ('tope', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tope')),
                ('union', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unión')),
                ('tipo_stock_insumos', models.CharField(blank=True, choices=[('Ingreso', 'Ingreso de Stock'), ('Egreso', 'Egreso de Stock')], max_length=30, null=True, verbose_name='Tipo de Stock Insumos')),
                ('fecha_stock_insumo', models.DateField(default=datetime.date.today, verbose_name='Fecha Stock Insumo')),
            ],
            options={
                'verbose_name': 'Stock Insumos',
                'verbose_name_plural': 'Stocks Insumos',
            },
        ),
        migrations.CreateModel(
            name='StockCortinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='M² Tela ')),
                ('tipo_stock_cotinas', models.CharField(blank=True, choices=[('Ingreso', 'Ingreso de Stock'), ('Egreso', 'Egreso de Stock')], max_length=30, null=True, verbose_name='Tipo de Stock Cotinas')),
                ('fecha_stock_cortina', models.DateField(default=datetime.date.today, verbose_name='Fecha Stock Cortina')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_articulo', to='tipocortina.cortina')),
            ],
            options={
                'verbose_name': 'Stock Cortinas',
                'verbose_name_plural': 'Stocks Cortinas',
            },
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
