# Generated by Django 5.1.6 on 2025-03-24 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stockinismos_stockcortinas_delete_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stockcortinas',
            old_name='fecha_stock_cortina',
            new_name='fecha_stock_cortinas',
        ),
        migrations.RenameField(
            model_name='stockinismos',
            old_name='fecha_stock_insumo',
            new_name='fecha_stock_insumos',
        ),
        migrations.AddField(
            model_name='stockinismos',
            name='estado_stock_insumos',
            field=models.CharField(choices=[('Ingreso', 'Comprometido'), ('Egreso', 'Aplicado')], max_length=30, null=True, verbose_name='Estado Stock'),
        ),
        migrations.AlterField(
            model_name='stockcortinas',
            name='articulo',
            field=models.CharField(max_length=180, null=True, verbose_name='Cortina Descripción'),
        ),
        migrations.AlterField(
            model_name='stockcortinas',
            name='tipo_stock_cotinas',
            field=models.CharField(choices=[('Ingreso', 'Ingreso de Stock'), ('Egreso', 'Egreso de Stock')], max_length=30, null=True, verbose_name='Tipo de Stock Cotinas'),
        ),
        migrations.AlterField(
            model_name='stockinismos',
            name='tipo_stock_insumos',
            field=models.CharField(choices=[('Ingreso', 'Ingreso de Stock'), ('Egreso', 'Egreso de Stock')], max_length=30, null=True, verbose_name='Tipo de Stock Insumos'),
        ),
    ]
