# Generated by Django 5.1.6 on 2025-03-24 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_rename_fecha_stock_cortina_stockcortinas_fecha_stock_cortinas_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StockInismos',
            new_name='StockInsumos',
        ),
    ]
