# Generated by Django 5.1.6 on 2025-03-24 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_rename_stockinismos_stockinsumos'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockcortinas',
            name='estado_stock_cortinas',
            field=models.CharField(choices=[('Ingreso', 'Comprometido'), ('Egreso', 'Aplicado')], max_length=30, null=True, verbose_name='Estado Stock'),
        ),
    ]
