# Generated by Django 5.1.6 on 2025-03-21 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='variablesModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var_cadena', models.DecimalField(decimal_places=2, default=0, help_text='Valor de la variable cadena', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Variable Cadena')),
            ],
            options={
                'verbose_name': 'Variables Generales',
                'verbose_name_plural': 'Variables Generales',
            },
        ),
    ]
