# Generated by Django 5.1.6 on 2025-03-21 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesmodels',
            name='enrrole',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor agregado de tela enrolle', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Variable Enrolle'),
        ),
    ]
