# Generated by Django 5.1.6 on 2025-03-21 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_variablesmodels_enrrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablesmodels',
            old_name='enrrole',
            new_name='var_enrrole',
        ),
    ]
