# Generated by Django 5.1.6 on 2025-03-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_rename_enrrole_variablesmodels_var_enrrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variablesmodels',
            old_name='var_enrrole',
            new_name='var_enrolle',
        ),
    ]
