# Generated by Django 5.1.6 on 2025-03-22 08:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0004_rename_var_enrrole_variablesmodels_var_enrolle'),
    ]

    operations = [
        migrations.AddField(
            model_name='variablesmodels',
            name='var_tapa_zocalos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='2 zolalos por cortina', max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tapa Zocalos'),
        ),
    ]
