# Generated by Django 5.1.6 on 2025-03-10 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(max_length=50, verbose_name='Telefono')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('cod_postal', models.IntegerField(verbose_name='CP')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('cbu', models.CharField(blank=True, max_length=50, null=True, verbose_name='CBU')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietario',
            },
        ),
    ]
