# Generated by Django 5.1.6 on 2025-03-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=100, verbose_name='Nombre')),
                ('direccion', models.CharField(default='', max_length=100, verbose_name='Dirección')),
                ('telefono', models.CharField(default='', max_length=100, verbose_name='Telefono')),
                ('ciudad', models.CharField(default='', max_length=100, verbose_name='Ciudad')),
                ('cod_postal', models.IntegerField(default=0, verbose_name='CP')),
                ('email', models.CharField(default='', max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Propietario',
                'verbose_name_plural': 'Propietario',
            },
        ),
    ]
