# Generated by Django 5.1.6 on 2025-03-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propietario',
            name='cbu',
            field=models.CharField(default=1, max_length=50, verbose_name='CBU'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='propietario',
            name='ciudad',
            field=models.CharField(max_length=50, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='cod_postal',
            field=models.IntegerField(verbose_name='CP'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='direccion',
            field=models.CharField(max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='propietario',
            name='telefono',
            field=models.CharField(max_length=50, verbose_name='Telefono'),
        ),
    ]
