# Generated by Django 5.1.6 on 2025-03-03 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propietario', '0002_propietario_cbu_alter_propietario_ciudad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='cbu',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='CBU'),
        ),
    ]
