# Generated by Django 5.1.6 on 2025-03-10 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100, unique=True, verbose_name='Razón social')),
                ('fecha_creacion', models.DateField(default=datetime.date.today, verbose_name='Fecha de Creación')),
                ('direccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=25, null=True, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='Colocador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Razón social')),
                ('fecha_creacion', models.DateField(default=datetime.date.today, verbose_name='Fecha de Creación')),
                ('telefono', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Colocador',
                'verbose_name_plural': 'Colocadores',
                'ordering': ['nombre'],
            },
        ),
    ]
