# Generated by Django 5.1.6 on 2025-03-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='localidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='piso',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Piso'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='provincia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='colocador',
            name='nombre',
            field=models.CharField(max_length=150, unique=True, verbose_name='Apellido Nombre'),
        ),
    ]
