# Generated by Django 5.1.6 on 2025-03-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_alter_cliente_direccion_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colocador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Razón social')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('telefono', models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Colocador',
                'verbose_name_plural': 'Colocadores',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['razon_social'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Teléfono'),
        ),
    ]
