# Generated by Django 5.1.6 on 2025-03-02 18:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_cliente_fecha_creacion_colocador_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='colocador',
            name='fecha_creacion',
            field=models.DateTimeField(default=datetime.date.today, verbose_name='Fecha de Creación'),
        ),
    ]
