# Generated by Django 5.1.6 on 2025-03-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_alter_cliente_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.DateField(blank=True, max_length=100, null=True, verbose_name='Dirección'),
        ),
    ]
