# Generated by Django 5.1.6 on 2025-03-02 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0009_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colocador',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Razón social'),
        ),
    ]
