# Generated by Django 5.1.6 on 2025-03-22 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tipocortina', '0001_initial'), ('tipocortina', '0002_tipocaida_tipomando_tiptubo_and_more'), ('tipocortina', '0003_tipocortina_cadena_tipocortina_peso_cadena_and_more'), ('tipocortina', '0004_alter_tipocortina_cadena'), ('tipocortina', '0005_tipocortina_metros_totales_alter_tipocortina_cadena'), ('tipocortina', '0006_alter_tipocortina_cadena_and_more'), ('tipocortina', '0007_alter_tipocortina_costo_total_and_more'), ('tipocortina', '0008_alter_tipocortina_zocalo')]

    initial = True

    dependencies = [
        ('ordendetrabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Cortina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Cortina')),
                ('codigo', models.CharField(blank=True, max_length=25, null=True, verbose_name='Código')),
                ('caracteristicas', models.TextField(blank=True, null=True, verbose_name='Caracteristicas')),
                ('tipo_cortina', models.BooleanField(default=False, verbose_name='Cortina de Confección ')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipocortina.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Tipo de Cortina',
                'verbose_name_plural': 'Tipos de Cortina',
            },
        ),
        migrations.CreateModel(
            name='Tipocaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Caída',
                'verbose_name_plural': 'Tipos de Caída',
            },
        ),
        migrations.CreateModel(
            name='Tipomando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Mando',
                'verbose_name_plural': 'Tipos de Mando',
            },
        ),
        migrations.CreateModel(
            name='Tiptubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Tubo',
                'verbose_name_plural': 'Tipos de Tubo',
            },
        ),
        migrations.CreateModel(
            name='TipoCortina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alto (mts)')),
                ('ancho', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancho (mts)')),
                ('metros_cuadrados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metros²')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('costo', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0.0, help_text='valor calculado automáticamente', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Mano Obra')),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Otros Costos')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('total', models.DecimalField(decimal_places=2, default=0.0, help_text='valor calculado automáticamente', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('ganancia_neta', models.DecimalField(decimal_places=2, default=0.0, help_text='valor calculado automáticamente', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ganancia Neta')),
                ('ganancia_porcentaje', models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Ganancia')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortina', to='tipocortina.cortina')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordendetrabajo.ordentrabajo', verbose_name='Orden Trabajo')),
                ('articulo_descripcion', models.CharField(blank=True, max_length=180, null=True, verbose_name='Art Descripción')),
                ('caida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tipocaida', verbose_name='Tipo de Caída')),
                ('mando', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tipomando', verbose_name='Tipo de Mando')),
                ('tubo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tiptubo', verbose_name='Tipo de Tubo')),
                ('cadena', models.DecimalField(blank=True, decimal_places=2, help_text='valor calculado automáticamente', max_digits=6, null=True, verbose_name='Cadena')),
                ('peso_cadena', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Cadena')),
                ('tapa_zocalo', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tapa Zocalo')),
                ('tope', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tope')),
                ('union', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unión')),
                ('zocalo', models.DecimalField(blank=True, decimal_places=2, help_text='valor calculado automáticamente', max_digits=6, null=True, verbose_name='Zocalo')),
                ('metros_totales', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='valor calculado automáticamente', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='M² Tela ')),
            ],
            options={
                'verbose_name': 'Cortina',
                'verbose_name_plural': 'Cortinas',
            },
        ),
    ]
