# Generated by Django 5.1.6 on 2025-03-10 08:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ordendetrabajo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Modelo')),
            ],
        ),
        migrations.CreateModel(
            name='Cortina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Cortina')),
                ('codigo', models.CharField(blank=True, max_length=25, null=True, verbose_name='Código')),
                ('caracteristicas', models.TextField(blank=True, null=True, verbose_name='Caracteristicas')),
                ('tipo_cortina', models.BooleanField(default=False, verbose_name='Cortina de Confección ')),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tipocortina.modelo', verbose_name='Modelo')),
            ],
            options={
                'verbose_name': 'Tipo de Cortina',
                'verbose_name_plural': 'Tipos de Cortina',
            },
        ),
        migrations.CreateModel(
            name='TipoCortina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alto', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alto (mts)')),
                ('ancho', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancho (mts)')),
                ('metros_cuadrados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metros²')),
                ('mando_derecho', models.BooleanField(default=False, verbose_name='Mando Derecho')),
                ('mando_izquierdo', models.BooleanField(default=False, verbose_name='Mando Izquierdo')),
                ('cantidad', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario')),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total')),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Mano Obra')),
                ('otros_costos', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Otros Costos')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total')),
                ('precio_venta', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta')),
                ('ganancia_neta', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ganancia Neta')),
                ('ganancia_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Ganancia')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortina', to='tipocortina.cortina')),
                ('orden_trabajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordendetrabajo.ordentrabajo', verbose_name='Orden Trabajo')),
            ],
            options={
                'verbose_name': 'Cortina',
                'verbose_name_plural': 'Cortinas',
            },
        ),
    ]
