# Generated by Django 5.1.6 on 2025-03-23 13:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipocaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Caída',
                'verbose_name_plural': 'Tipos de Caída',
            },
        ),
        migrations.CreateModel(
            name='Tipomando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Mando',
                'verbose_name_plural': 'Tipos de Mando',
            },
        ),
        migrations.CreateModel(
            name='Tiptubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Tubo',
                'verbose_name_plural': 'Tipos de Tubo',
            },
        ),
        migrations.RemoveField(
            model_name='tipocortina',
            name='mando_derecho',
        ),
        migrations.RemoveField(
            model_name='tipocortina',
            name='mando_izquierdo',
        ),
        migrations.RemoveField(
            model_name='tipocortina',
            name='metros_cuadrados',
        ),
        migrations.RemoveField(
            model_name='tipocortina',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='articulo_descripcion',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Art Descripción'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='cadena',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='valor calculado automáticamente', max_digits=6, null=True, verbose_name='Cadena'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='metros_totales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='valor calculado automáticamente', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='M² Tela '),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='peso_cadena',
            field=models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Cadena'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='tapa_zocalo',
            field=models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tapa Zocalo'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='tope',
            field=models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tope'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='union',
            field=models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unión'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='zocalo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='valor calculado automáticamente', max_digits=6, null=True, verbose_name='Zocalo'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alto (mts)'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancho (mts)'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='valor calculado automáticamente', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ganancia_neta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='valor calculado automáticamente', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ganancia Neta'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ganancia_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Ganancia'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='valor calculado automáticamente', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_cuadrados', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='M² Tela ')),
                ('cadena', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Cadena')),
                ('zocalo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Zocalo')),
                ('tapa_zocalo', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tapa Zocalo')),
                ('peso_cadena', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Cadena')),
                ('tope', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tope')),
                ('union', models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unión')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_articulo', to='tipocortina.cortina')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='caida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tipocaida', verbose_name='Tipo de Caída'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='mando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tipomando', verbose_name='Tipo de Mando'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='tubo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tiptubo', verbose_name='Tipo de Tubo'),
        ),
    ]
