# Generated by Django 5.1.6 on 2025-03-21 08:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipocaida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Caída',
                'verbose_name_plural': 'Tipos de Caída',
            },
        ),
        migrations.CreateModel(
            name='Tipomando',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Mando',
                'verbose_name_plural': 'Tipos de Mando',
            },
        ),
        migrations.CreateModel(
            name='Tiptubo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name': 'Tipo de Tubo',
                'verbose_name_plural': 'Tipos de Tubo',
            },
        ),
        migrations.RemoveField(
            model_name='tipocortina',
            name='mando_derecho',
        ),
        migrations.RemoveField(
            model_name='tipocortina',
            name='mando_izquierdo',
        ),
        migrations.RemoveField(
            model_name='tipocortina',
            name='precio_venta',
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='articulo_descripcion',
            field=models.CharField(blank=True, max_length=180, null=True, verbose_name='Art Descripción'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alto (mts)'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancho (mts)'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Mano Obra'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ganancia_neta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ganancia Neta'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ganancia_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Ganancia'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='otros_costos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Otros Costos'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='caida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tipocaida', verbose_name='Tipo de Caída'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='mando',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tipomando', verbose_name='Tipo de Mando'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='tubo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tiptubo', verbose_name='Tipo de Tubo'),
        ),
    ]
