# Generated by Django 5.1.6 on 2025-02-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocortina',
            name='alto',
            field=models.CharField(help_text='160', max_length=50, verbose_name='Alto'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ancho',
            field=models.CharField(help_text='120', max_length=50, verbose_name='Ancho'),
        ),
    ]
