# Generated by Django 5.1.6 on 2025-03-11 20:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocortina',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alto (mts)'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancho (mts)'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Mano Obra'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ganancia_neta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ganancia Neta'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ganancia_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='% Ganancia'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='otros_costos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Otros Costos'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
    ]
