# Generated by Django 5.1.6 on 2025-03-24 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0001_initial'),
        ('tipocortina', '0002_tipocaida_tipomando_tiptubo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tiptubo',
            new_name='Tipotubo',
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orden_tipocortina', to='ordendetrabajo.ordentrabajo', verbose_name='Orden Trabajo'),
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
