# Generated by Django 5.1.6 on 2025-03-21 09:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0002_tipocaida_tipomando_tiptubo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocortina',
            name='cadena',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cadena'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='peso_cadena',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Cadena'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='tapa_zocalo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tapa Zocalo'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='tope',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tope'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='union',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unión'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='zocalo',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Zocalo'),
        ),
    ]
