# Generated by Django 5.1.6 on 2025-03-13 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0001_initial'),
        ('tipocortina', '0002_alter_tipocortina_alto_alter_tipocortina_ancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocortina',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ordendetrabajo.ordentrabajo', verbose_name='Orden Trabajo'),
        ),
    ]
