# Generated by Django 5.1.6 on 2025-02-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0003_cortina_alter_tipocortina_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocortina',
            name='alto',
            field=models.CharField(default=0, help_text='160', max_length=50, verbose_name='Alto'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ancho',
            field=models.CharField(default=0, help_text='120', max_length=50, verbose_name='Ancho'),
        ),
    ]
