# Generated by Django 5.1.6 on 2025-03-13 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0003_alter_tipocortina_orden_trabajo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocortina',
            name='precio_venta',
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='articulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cortina', to='tipocortina.cortina'),
        ),
    ]
