# Generated by Django 5.1.6 on 2025-03-25 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0004_cortina_fabricacion_alter_cortina_tipo_cortina'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortina',
            name='costo_m2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo M²'),
        ),
    ]
