# Generated by Django 5.1.6 on 2025-03-21 13:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0004_alter_tipocortina_cadena'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocortina',
            name='metros_totales',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='M² Tela '),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='cadena',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Cadena'),
        ),
    ]
