# Generated by Django 5.1.6 on 2025-02-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0004_alter_tipocortina_alto_alter_tipocortina_ancho'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocortina',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total'),
            preserve_default=False,
        ),
    ]
