# Generated by Django 5.1.6 on 2025-02-28 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0005_tipocortina_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocortina',
            name='alto',
            field=models.CharField(default=0, max_length=50, verbose_name='Alto (mts)'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ancho',
            field=models.CharField(default=0, max_length=50, verbose_name='Ancho (mts)'),
        ),
    ]
