# Generated by Django 5.1.6 on 2025-03-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0005_cortina_color_tipocortina_articulo_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cortina',
            name='color',
        ),
    ]
