# Generated by Django 5.1.6 on 2025-03-02 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0006_alter_tipocortina_alto_alter_tipocortina_ancho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocortina',
            name='orden',
        ),
    ]
