# Generated by Django 5.1.6 on 2025-03-21 14:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0006_alter_tipocortina_cadena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocortina',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='valor calculado automáticamente', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ganancia_neta',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='valor calculado automáticamente', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ganancia Neta'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='valor calculado automáticamente', max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total'),
        ),
    ]
