# Generated by Django 5.1.6 on 2025-03-22 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0007_alter_tipocortina_costo_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocortina',
            name='zocalo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='valor calculado automáticamente', max_digits=6, null=True, verbose_name='Zocalo'),
        ),
    ]
