# Generated by Django 5.1.6 on 2025-03-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0008_alter_tipocortina_options_cortina_tipo_cortina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cortina',
            name='codigo',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='cortina',
            name='modelo',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='cortina',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='cortina',
            name='nombre',
            field=models.CharField(max_length=100, unique=True, verbose_name='Cortina'),
        ),
    ]
