# Generated by Django 5.1.6 on 2025-03-22 14:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0001_squashed_0008_alter_tipocortina_zocalo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocortina',
            name='peso_cadena',
            field=models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Cadena'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='tapa_zocalo',
            field=models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tapa Zocalo'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='tope',
            field=models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tope'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='union',
            field=models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unión'),
        ),
    ]
