# Generated by Django 5.1.6 on 2025-03-02 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0009_cortina_codigo_cortina_modelo_cortina_observaciones_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Modelo')),
            ],
        ),
        migrations.AlterField(
            model_name='cortina',
            name='modelo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='tipocortina.modelo', verbose_name='Modelo'),
            preserve_default=False,
        ),
    ]
