# Generated by Django 5.1.6 on 2025-03-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0009_alter_tipocortina_peso_cadena_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocortina',
            name='metros_cuadrados',
        ),
    ]
