# Generated by Django 5.1.6 on 2025-03-22 19:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0010_remove_tipocortina_metros_cuadrados'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_cuadrados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metros²')),
                ('cadena', models.DecimalField(blank=True, decimal_places=2, help_text='valor calculado automáticamente', max_digits=6, null=True, verbose_name='Cadena')),
                ('zocalo', models.DecimalField(blank=True, decimal_places=2, help_text='valor calculado automáticamente', max_digits=6, null=True, verbose_name='Zocalo')),
                ('tapa_zocalo', models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tapa Zocalo')),
                ('peso_cadena', models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Cadena')),
                ('tope', models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tope')),
                ('union', models.IntegerField(blank=True, help_text='valor calculado automáticamente', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unión')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_articulo', to='tipocortina.cortina')),
                ('caida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tipocaida', verbose_name='Tipo de Caída')),
                ('mando', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tipomando', verbose_name='Tipo de Mando')),
                ('tubo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tipocortina.tiptubo', verbose_name='Tipo de Tubo')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
            },
        ),
    ]
