# Generated by Django 5.1.6 on 2025-03-02 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0011_alter_cortina_nombre_alter_modelo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocortina',
            name='alto',
        ),
        migrations.RemoveField(
            model_name='tipocortina',
            name='ancho',
        ),
    ]
