# Generated by Django 5.1.6 on 2025-03-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0011_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='caida',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='mando',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='tubo',
        ),
    ]
