# Generated by Django 5.1.6 on 2025-03-02 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0012_remove_tipocortina_alto_remove_tipocortina_ancho'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocortina',
            name='alto',
            field=models.CharField(default=0, max_length=50, verbose_name='Alto (mts)'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='ancho',
            field=models.CharField(default=0, max_length=50, verbose_name='Ancho (mts)'),
        ),
    ]
