# Generated by Django 5.1.6 on 2025-03-22 19:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0013_alter_stock_cadena_alter_stock_peso_cadena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='cadena',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Cadena'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='peso_cadena',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Peso Cadena'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tapa_zocalo',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tapa Zocalo'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='tope',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tope'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='union',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unión'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='zocalo',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6, null=True, verbose_name='Zocalo'),
        ),
    ]
