# Generated by Django 5.1.6 on 2025-03-23 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0014_alter_stock_cadena_alter_stock_peso_cadena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='metros_cuadrados',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6, null=True, verbose_name='M² Tela '),
        ),
    ]
