# Generated by Django 5.1.6 on 2025-03-02 03:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0015_tipocortina_observaciones_tipocortina_otros_costos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocortina',
            name='precio_venta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Precio Venta'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='otros_costos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total'),
        ),
    ]
