# Generated by Django 5.1.6 on 2025-03-23 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0016_tipocortina_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipocortina',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alto (mts)'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancho (mts)'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Unitario'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Mano Obra'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='valor calculado automáticamente', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='otros_costos',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Otros Costos'),
        ),
    ]
