# Generated by Django 5.1.6 on 2025-03-02 03:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0016_tipocortina_precio_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocortina',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Mano Obra'),
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Costo Total'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='otros_costos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Otros Costos'),
        ),
    ]
