# Generated by Django 5.1.6 on 2025-03-02 04:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0018_tipocortina_ganacia_neta_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipocortina',
            old_name='ganacia_porcentaje',
            new_name='ganancia_porcentaje',
        ),
        migrations.RemoveField(
            model_name='tipocortina',
            name='ganacia_neta',
        ),
        migrations.AddField(
            model_name='tipocortina',
            name='ganancia_neta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ganancia Neta'),
        ),
    ]
