# Generated by Django 5.1.6 on 2025-03-02 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0007_remove_ordentrabajo_ganancia_and_more'),
        ('tipocortina', '0019_rename_ganacia_porcentaje_tipocortina_ganancia_porcentaje_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocortina',
            name='orden_trabajo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ordendetrabajo.ordentrabajo', verbose_name='Orden Trabajo'),
            preserve_default=False,
        ),
    ]
