# Generated by Django 5.1.6 on 2025-03-02 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordendetrabajo', '0007_remove_ordentrabajo_ganancia_and_more'),
        ('tipocortina', '0020_tipocortina_orden_trabajo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocortina',
            name='orden_trabajo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ordendetrabajo.ordentrabajo', verbose_name='Orden Trabajo'),
        ),
    ]
