# Generated by Django 5.1.6 on 2025-03-03 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0021_alter_tipocortina_orden_trabajo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipocortina',
            name='metros_cuadrados',
            field=models.IntegerField(default=0, max_length=50, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Metros Cuadrados'),
        ),
    ]
