# Generated by Django 5.1.6 on 2025-03-03 17:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0022_tipocortina_metros_cuadrados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocortina',
            name='metros_cuadrados',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metros²'),
        ),
    ]
