# Generated by Django 5.1.6 on 2025-03-04 13:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tipocortina', '0023_alter_tipocortina_metros_cuadrados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipocortina',
            name='alto',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Alto (mts)'),
        ),
        migrations.AlterField(
            model_name='tipocortina',
            name='ancho',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ancho (mts)'),
        ),
    ]
