# Generated by Django 5.1.6 on 2025-03-04 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipocortina', '0024_alter_tipocortina_alto_alter_tipocortina_ancho'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_cuadrados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metros²')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercaderia', to='tipocortina.cortina')),
            ],
            options={
                'verbose_name': 'Mercaderia',
                'verbose_name_plural': 'Mercaderia',
            },
        ),
    ]
