# Generated by Django 5.1.6 on 2025-03-10 08:27

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tipocortina', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mercaderia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metros_cuadrados', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metros²')),
                ('cantidad', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Cantidad Unid.')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='costo')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name='Fecha Ingreso')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mercaderia', to='tipocortina.cortina')),
            ],
            options={
                'verbose_name': 'Mercaderia',
                'verbose_name_plural': 'Mercaderia',
            },
        ),
    ]
