# Generated by Django 5.1.6 on 2025-03-04 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercaderia',
            name='fecha_creacion',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Ingreso'),
        ),
    ]
