# Generated by Django 5.1.6 on 2025-03-11 20:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mercaderia',
            name='costo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='costo'),
        ),
        migrations.AlterField(
            model_name='mercaderia',
            name='metros_cuadrados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Metros²'),
        ),
    ]
