# Generated by Django 5.1.6 on 2025-03-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mercaderia', '0002_mercaderia_fecha_creacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mercaderia',
            old_name='fecha_creacion',
            new_name='fecha_ingreso',
        ),
    ]
